version: '3.7'

services:
  db:
    image: postgres
    restart: always
    volumes:
     - pgdata:/var/lib/postgresql/data
    environment:
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_USER=postgres
     - POSTGRES_DB=twix_dev
    ports:
      - 5432:5432
volumes:
  pgdata: